include: package:very_good_analysis/analysis_options.1.0.1.yaml

analyzer:
  exclude:
    - 'lib/di_setup.config.dart'

linter:
  rules:
    unawaited_futures: false
    curly_braces_in_flow_control_structures: false
    library_prefixes: false
    public_member_api_docs: false
    omit_local_variable_types: false
    sort_constructors_first: false