name: cam_scanner


version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Http Api
  http: ^1.3.0

  # CamScanner
  edge_detection: ^1.0.5

  # PDF generation - path
  path_provider: ^2.0.14
  uuid: ^4.5.1
  pdf: ^3.10.1

  # PDF View
  printing: ^5.10.0
  awesome_dialog: ^3.2.1

  # Merge part
  carousel_slider: ^5.0.0
  r_dotted_line_border: ^0.1.0

  ## Dependency injection
  get_it: ^8.0.3
  injectable: ^2.5.0

  #Font icons
  font_awesome_flutter: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  path: any

  # Injectable and dependency injection
  build_runner:
  injectable_generator: ^2.7.0
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true